# Generated by Django 3.1.2 on 2020-10-03 04:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0004_auto_20201002_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='date_joined',
            field=models.DateField(default=datetime.datetime(2020, 10, 2, 22, 26, 46, 250184), verbose_name='Fecha_de_registro'),
        ),
        migrations.AlterField(
            model_name='type',
            name='names',
            field=models.CharField(max_length=150, unique=True, verbose_name='Nombres'),
        ),
    ]
