# Generated by Django 3.1.3 on 2020-11-15 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Nombre')),
                ('categoria', models.CharField(max_length=100, verbose_name='Categoría')),
                ('pcompra', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Precio de compra')),
                ('pventa', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Precio de venta')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['id'],
            },
        ),
    ]
